### ISSUE TITLE
Add ability for FBSession to load FBAppId, WindowsAppID from resources

### ISSUE THREAD

**Issue by ekalbredneb** [Microsoft/winsdkfb#10]
On phone in particular, if an app is tombstoned that session can lose its information like token, app IDs, etc., and the app developer shouldn't have to write code to reset these values.  Rather, the session should just load them from string resources with a well-known name.

**Comment by TedHoward** [comment]
That assumes that every app has string resources. Of course, the feature could be implemented in a way to still allow programmatic setting of these values which is an API design that will always work.

**Comment by ekalbredneb** [comment]
Yes, this may be a problem for unusual cases, like a desktop (Win32) app using the SDK.  For a regular Store (modern UI) app, adding a resources.resw file and inserting a couple of well-known values ends up simplifying the programming model quite a bit, though, so it's worth doing.  As long as the properties on FBSession are writable, the app can still handle this appropriately, and I don't see any reason to make them read-only, so we're probably okay there.

**Comment by TedHoward** [comment]
I agree that leaving them writeable is very good. I also agree that reading
them from some standard resources file will be helpful for Windows-only
codebases.

However, I speak from experience. We have to jump through hoops at times to
support Android because some Android libraries do the "load the values from
resources" scheme, in fact I think the official Facebook SDK does this. iOS
often does the same with their plist resource files. Our game compiles for
linux, osx, win32, ios, winrt, winrt/phone, html, android, android/fire,
android/<a couple others>, and someday win10. Supporting the OS-specific
configuration files for each platform is a drain on our dev resources and
error-prone( because you always forget to update one of them, right?).

-ted

**Comment by ekalbredneb** [comment]
Updated the title of this issue to reflect current understanding that we won't make the resource file the exclusive way to set app IDs.

**Comment by yodurr** [comment]
Open Ask: identify an optional model to use resources to store the FB App ID.

**Comment by sanjeevdwivedi** [comment]
The C# SDK does this by having a [XML] (file https://github.com/facebook-csharp-sdk/facebook-winclient-sdk/blob/master/Samples/BasicApp-Win81-Universal/FacebookConfig.xml) Why not just do that? The Windows manifest is not extensible AFAIK, so this seems to be a logical step to keep the configuration outside.

**Comment by alakshmi1030** [comment]
Developers can load the FB App ID and Windows App ID from a Resources.resw file if they would like to avoid hard-coded strings in their source. See the Login-Cpp sample app to see an example of this.
