### ISSUE TITLE
Keep being "logged in" after app shutdown?

### ISSUE THREAD

**Issue by Whyser** [Microsoft/winsdkfb#166]
Hello,

On Android and iOS, once a user has logged in to Facebook in the app, they no longer needs to login again if they shutdown the app (the Access Token is saved somewhere I believe).

However, on the UWP version of the winfbsdk, I can login, shut down the app, but then when I open the app I have to login again (although, I don't need to enter my credentials again, which would indicate that there is some access token saved somewhere).

My wanted behavior is that of the Android and iOS version. So my question is: is there some way to "know" that the user actually is logged in, so that I can just in the "background" invoke the "Login(...)" method, instead of them either pressing a button or being forced a Login-dialog?

**Comment by adiviness** [comment]
We do save the access token and reuse it if it hasn't expired. If it hasn't expired than the normal `LoginAsync` functionality will simply use that instead of going through the process of entering credentials. What you can do to check if the user has logged in previously and their access token is still good without the possibility of a dialog appearing is to call `LoginAsync` with `SessionLoginBehavior::Silent` as a parameter during your application start up. You will then be able to check the `FBResult` that is returned and continue with the credential-based login flow with another call to `LoginAsync` if necessary.

**Comment by Whyser** [comment]
Okay thank you for this information! Wouldn't it be logical to actually return that the user is logged in (without actually issuing a login), if the access token is indeed valid?

**Comment by adiviness** [comment]
That is what we do, we do not store any login details, just the access token.

**Comment by Whyser** [comment]
Sorry for the late answer! I've double-checked (used the develop branch), and it seems that if I follow the following procedure I will not remain "logged in".

1. Start app
2. Login with credentials (fill the popup) and succeed
3. Close app
4. Set breakpoint somewhere and where you have access to FBSession.ActiveSession
5. Observe that AccessTokenData on the ActiveSession object is null.

HOWEVER, if I call LoginAsync(...), there will be a silent login. And my AccessTokenData will be "populated". Why isn't the AccessTokenData populated before (if I was previously logged in), so that I don't have to perform a sneaky login (which in worst case will trigger a popup when the user doesn't want it)?

Thanks!

**Comment by adiviness** [comment]
That is the intended behavior of the sdk. We cannot implement the behavior you are describing because the `FBSession` object returned by `FBSession::ActiveSession` must have certain fields set according to a developer's preferences before login can occur (such as the various app IDs and facebook graph API version). On a successful login some graph calls are made to gather basic information about the user that has logged in (found at `FBSession::User` after login) and we need these `FBSession` fields set properly in order for those calls to be successful. 

In the described worst case scenario, a developer has the ability to prevent it by specifying `SessionLoginBehavior::Silent` when they call `FBSession::LoginAsync`.

**Comment by Whyser** [comment]
Thanks for the quick response! 

I understand the use of the silent behavior and will probably use it. But why can't I have access to the access token? It's there somewhere, why not let the developer use it? :)

**Comment by adiviness** [comment]
You actually can access it! After a successful login, the string for the current access token can be found at `FBSession::ActiveSession->AccessTokenData->AccessToken`.

**Comment by Whyser** [comment]
I meant: Why can't I access it before login, if you guys can perform a silent login with it? :)

**Comment by adiviness** [comment]
If you would really like the access token before any login has occurred, it is written to an encrypted file in the app's local folder. I would suggest taking a look at `FBSession::CheckForExistingToken` for more information on how to access and read that file. However, there is no guarantee that the token saved there has not expired, or that the file even exists at all. And altering the file may cause the sdk to stop functioning correctly until it is deleted, so I don't really recommend messing with it.

We may also change the format of the file (what data is stored in it, ordering, etc.) or get rid of it entirely if it turns out there's a better way to store the information in it. It really isn't something that can be depended upon to not change from one version of the sdk to the next since it isn't meant to be accessed by anything other than private `FBSession` functions.

Because of the caveats surrounding the access token's usability/existence before `FBSession::LoginAsync` has been called I would guess that is why it is not easily accessible before login.

**Comment by Whyser** [comment]
Thank you for taking the time to explain this so thorough! I will keep away from meddling with the encrypted file! ;)
