### ISSUE TITLE
Multiple LogInasync fails

### ISSUE THREAD

**Issue by vladcristea** [Microsoft/winsdkfb#169]
Hi,

I have the following scenario: On a page I have a loginasync silent mode and this call is made every time a refresh button is pressed. The result is the following one: the user is logged in, the second call gives me an error and I don't have an access toke anymore, the third call is working fine, the fourth not and so on. Is that the expected behavior? I wanted this check in order to catch all possible cases.

Thanks,
Vlad Cristea

**Comment by adiviness** [comment]
So when you call `FBSession::LoginAsync` with `SessionLoginBehavior::Silent` what happens is that the sdk checks for a previously saved access token and reuses it if it has not expired yet. When `FBSession::LoginAsync` is called when a user is already logged in, we assume that this login call is re-requesting some permissions. Because the silent login behavior can't initiate any login UI for the user to accept re-requested permissions it automatically fails (even if the permissions being requested are the same). Because it failed, the user is then logged out. When you try to login again, `FBSession` knows that it is logged out and simply reuses the saved token and everything is fine again. This is why the login calls alternate between successful and not.

This behavior makes some amount of sense when in the context of wanting to re-request permissions, but `SessionLoginBehavior::Silent` should be smarter about it and check if there is actually any difference in the requested permissions before failing to log in.

I would suggest that you not have your refresh button use the silent login behavior because it will never fetch a new access token, even after this bug is fixed. Depending on what behavior you want the refresh button to exhibit you have a couple options.

If your refresh button is meant to ensure that the user is logged in, then you can check `FBSession::LoggedIn` first and then call `FBSession::LoginAsync` if the user is actually logged out.

 If your refresh button is meant to get a new access token each time it is pressed then calling `FBSession::LoginAsync` would not accomplish this and you will have to implement token extension manually.

**Comment by vladcristea** [comment]
Thank you for your reply and for the details. I wanted this behavior (to login on refresh) to handle the situation when a user removes the app from his facebook account during the time that the windows apps is running. so on refresh he should enter or authorize facebook again

**Comment by adiviness** [comment]
I see. For that scenario I'm not sure that it is currently detectable. The dialogs will display text describing the problem to the user but you won't receive an error message that describes that scenario precisely enough. Same goes for normal graph calls. We will need to look more into how we can more accurately describe errors to developers.

**Comment by adiviness** [comment]
A fix for getting logged out when calling `LoginAsync` multiple times has been merged into our `develop` branch so I'm going to go ahead and close this issue. I've opened a new issue (#181) for the problems related to the `FBError` class and our error reporting in the sdk since that sounds like they're at the heart of the problem you're having.
