### ISSUE TITLE
SDK doesn't support login via app on Windows Phone 8.1?

### ISSUE THREAD

**Issue by amishchenko** [Microsoft/winsdkfb#178]
LoginAsync without explicit behavior ignores facebook app, installed on a device and always shows webview UI (like in issue #125). Setting behavior parameter to WebAuth does noting.
Is this a bug or a functionality not implemented by design?

**Comment by adiviness** [comment]
This is by design, windows phone 8.1 only supports webview-based login flow.

**Comment by amishchenko** [comment]
But there is one possible realization (like here: https://code.msdn.microsoft.com/windowsapps/WindowsPhone-81-FaceBook-87eb2f69). Why it is not implemented?

**Comment by adiviness** [comment]
Currently login via `WebAuthenticationBroker` calls `AuthenticateAsync` which is not supported on windows phone 8.1. There are other methods that could be called for Windows phone 8.1 (`AuthenticateAndContinue`) but due to the nature of the "AndContinue" api pattern the behavior of that login flow would differ from every other login on every other configuration we support. Normally `FBSession::LoginAsync` is called which will attempt to login in some way or another and return an `FBResult` indicating the status of the login attempt. Because the "AndContinue" pattern leaves the app,  it would require a portion of the login flow (the entry point back into the app) to be implemented on a per app basis by a developer using the sdk.
