### ISSUE TITLE
Can't login with Web Account Provider on Win10 mobile Anniversary

### ISSUE THREAD

**Issue by anettex** [Microsoft/winsdkfb#211]
After update (system or fb application) FindAccountProviderAsync returns always null regardless of installed application.

**Comment by khouzam** [comment]
This is a result of the new Facebook application. Microsoft had written the first Facebook application for Windows Phone and included the functionality for the AccountProvider. Recently Facebook released their own app (much closer to the app on iOS and Android) and this application doesn't have support for logging in through an AccountProvider, that's why this now fails. I do not know if they have any plans to add this functionality back.
