### ISSUE TITLE
"No appropriate WebAccountProvider was found"

### ISSUE THREAD

**Issue by Whyser** [Microsoft/winsdkfb#216]
I get this message: "No appropriate WebAccountProvider was found" whenever I try to use the method: `FBSession.RefreshAccessToken()`. I can login successfully and use the API etc, but this method always fail. I tried googling the issue but found nothing. 
Is this a bug or some error on my side? If it is the latter, how do I deal with it?

Using the latest develop-branch when testing this on UWP (desktop).

**Comment by adiviness** [comment]
That method is not really meant to be called explicitly, it is only public because other parts of the sdk needed to call it. That method expects to have been logged in via the `SessionLoginBehavior::WebAccountProvider` behavior and I don't think there is currently an available account provider for facebook so that's why it's failing.

**Comment by Whyser** [comment]
Ahh thank you! I thought it was "public" because the offical facebook sdk has a public method called "RefreshAccessToken" also. :)
