### ISSUE TITLE
Nuget package currently needs to be manually built - consider hosting?

### ISSUE THREAD

**Issue by cbarkerms** [Microsoft/winsdkfb#22]
The nuget package today requires that you do a solution batch build, followed by running build-nupkg.cmd in the winsdkfb-master\winsdkfb-master\FBWinSDK\build\nuget folder.  In order to reduce developer friction, it would be preferable to have this package already built and publicly hosted somewhere.

**Comment by lil1029** [comment]
I agree with this suggestion. Also due to the moving pieces of VS, OS, SDK, there are often manual upgrades that needs to be done to the .vcxproj to update the project to whatever combination you currently have on your machine. At the very least, have a more complete README to include the different steps that needs to be taken in order to build the SDK. First, I did not even notice the build folder was there. It was through a series of trials and error that finally got the SDK to be build.

**Comment by yodurr** [comment]
we're looking into this.  Thanks for your patience.

**Comment by igrali** [comment]
Any update on this? 
Thanks!

**Comment by alakshmi1030** [comment]
Hey Igor, our team is currently working on getting the SDK ready for a Nuget package release. We are still going through some testing but we should have it ready soon.

**Comment by hosney** [comment]
Any updates?

**Comment by alakshmi1030** [comment]
Sorry for the delay - we are still working on some internal requirements before we can release the Nuget package publicly. We hope to have an update soon.

**Comment by alakshmi1030** [comment]
As of now there is a Nuget package of the SDK live located here:
https://www.nuget.org/packages/winsdkfb/

You can search for it in Visual Studio Nuget package manager.
