### ISSUE TITLE
FbSession::LoginAsync error

### ISSUE THREAD

**Issue by maioralin** [Microsoft/winsdkfb#222]
I've been using the winsdkfb for a while, but now, without doing any changes, i'm getting the following error when trying to login:

Login to use your Facebook account with Appname

and clicking the login link opens edge and the following message is given:
Success
SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Center for more information.

and I am unable to login

**Comment by adiviness** [comment]
what platform are you experiencing this problem on? what version of the sdk are you using?

**Comment by Trays** [comment]
Similar problem. It`s appeared after update winsdkfb to 0.12
Ordinary login with WebView only, appeared also with DefaultOrdering

**Comment by maioralin** [comment]
Hi,

I've just re-ran the project again today, and it works. Must have been a temporary issue.
Anyway, the version of sdk used is 0.11.20160720.1, in case someone encounters a similar problem.

Thanks,
Alin

**Comment by adiviness** [comment]
@Trays, the reason the problem would appear with `SessionLoginBehavior::WebView` and `SessionLoginBehavior::DefaultOrdering` is because the default ordering tries to log in via webview unless there is an account provider for facebook present. 

I've tried reproducing this by running our LoginCpp-UWP sample app on a windows 10 desktop (from the `master` branch, commit b20c40a1dcf71690edc3264ec5135e8e03ea1f6a) but I don't see this behavior. Are either of you still affected by this?

**Comment by maioralin** [comment]
@adiviness , no, it works fine for me now.
Thanks for the explanation.
