### ISSUE TITLE
Using a existing access token to do silent login

### ISSUE THREAD

**Issue by nuwannnz** [Microsoft/winsdkfb#225]
In my app I have stored access tokens from the azure app service when the user is registering. Is there a way I can  reuse those access tokens to do silent login if they are not expired? Isn't it a useful feature?

**Comment by adiviness** [comment]
I think this is possible, but I haven't personally tried it. 

What you would need to do is create an instance of `FBAccessTokenData` with the access token and other relevant data (take a look at FacebookAccessTokenData.h). Then you would create the `FBSession` singleton object and set `FBSession::AccessTokenData` to your `FBAccessTokenData` object. Then you would call `FBSession::LoginAsync` and it should see that it has an access token already and skip the login auth dialogs. Let me know if it works, I'm curious.

**Comment by nuwannnz** [comment]
Thanks for the reply. 
I have already tried it. But no success. Also I think the access token from azure has a problem. I'll let you know if I find a solution.

**Comment by nuwannnz** [comment]
Hey @adiviness  finally it works. 😃😃 
I created a `FBAccessTokenData` object with my token and set it as the current session's token data. And it worked. Also when creating the `FBAccessTokenData` object I dint find a way to extract the expiration date from the fb access token so I used `DateTimeOffset.Now`. 
Thanks for the help.

**Comment by nuwannnz** [comment]
Hey, what does this SessionLoginBehavior.Silent do?  when I tried to do login with this mode it resets the access token and login fails.

**Comment by adiviness** [comment]
The normal behavior of `FBSession::LoginAsync` is to try to use a previously saved access token and if necessary it will show a login dialog so it can acquire a valid token. `SessionLoginBehavior::Silent` will not show a login dialog if a valid access token is not available, it will instead return with the error. This is so that an app can choose to try and log in early if possible, but not be forced to show a login dialog until the developer really wants to (by calling `FBSession::LoginAsync` again with a different login behavor).
