### ISSUE TITLE
OUTDATED - NOT WORKING ANYMORE - Don't use it

### ISSUE THREAD

**Issue by cinosh07** [Microsoft/winsdkfb#269]
If you clear the cache of your app and try to re-log it will faill. Error 4201 on the debugger.
It appear at the same time on all installed version of our app.

If you still want to use your app until a bug fixe, don't clear the cache unless you'll get screwed.

**Comment by vegorovinno** [comment]
Remove these lines https://github.com/Microsoft/winsdkfb/blob/develop/winsdkfb/winsdkfb/winsdkfb.Shared/FacebookAccessTokenData.cpp#L161-L164

Someone who added them didn't think ahead at all.

**Comment by khouzam** [comment]
Thanks a lot for looking into this @vegorovinno,

I'll see to update the nuget package.

**Comment by kellylawson** [comment]
This is blocking some of my users from using our app - is there an ETA on getting a nuget package update?  Just found out about this today, would really like to get it fixed for the users that are unable to login.

**Comment by khouzam** [comment]
I'm working on it this week.

**Comment by kellylawson** [comment]
Fantastic!  Thanks for the quick reply, I really appreciate it. 

Kelly

**Comment by khouzam** [comment]
Hi @kellylawson 

Can you try the following nuget package: 
[winsdkfb.0.15.0.zip](https://github.com/Microsoft/winsdkfb/files/2447726/winsdkfb.0.15.0.zip)

If it works out, I'll merge this into master and publish it to nuget.

Thanks for the patience.

**Comment by kellylawson** [comment]
@khouzam Sorry I missed this yesterday!   I'll give it a try right now.

**Comment by kellylawson** [comment]
@khouzam I still get the same error as well:

![winsdkfb-version](https://user-images.githubusercontent.com/7303539/46547748-26651180-c88a-11e8-9885-c125dd7fc94b.PNG)

![fberror](https://user-images.githubusercontent.com/7303539/46547757-2d8c1f80-c88a-11e8-903c-eb51cdbf8a65.PNG)

Not sure what the fix was; it appears there's some misinterpretation from the FB oauth redirect response?  I'm using the WebView login behavior, not sure if that matters:

```
            FBResult result = await session.LoginAsync(
                new FBPermissions(new List<string>()),
                SessionLoginBehavior.WebView
                );
```

**Comment by khouzam** [comment]
Thanks @kellylawson,

This was my bad. I produced the build off the wrong change. It didn't actually include the fix. I've produced a new nuget package with the actual fix and have verified that I was getting the same `4201` error before the change and that it would succeed after the change. Please try again with the following package. The package is based on the 4f06f13d (which you can confirm with the winsdkfb.githash.txt file in the nuget package) commit which includes the login fix which is commit f214ba1d.

Here's the new package: [winsdkfb.0.15.0.zip](https://github.com/Microsoft/winsdkfb/files/2452168/winsdkfb.0.15.0.zip)


Sorry for the randomization.

@jmvillagra this seems to be the exact same error.

**Comment by khouzam** [comment]
Hi @kellylawson,

I tried it again and it looks like this is the right package. The modified date it right, Looking at the contents, it has the right hash value and installing it in our sample project works fine. Can you enable mixed mode debugging in your project and look at the module that is loaded in your process? It should have a version of 0.15.1810.5002

![image](https://user-images.githubusercontent.com/6656040/46578064-d67d6c00-c9a9-11e8-83c9-3eb68e831ba1.png)


Also if you go to your solution folder, there should be packages folder with a `winsdkfb.0.15.0` folder under it. Please delete the folder. Nuget caches the packages that you download and since I didn't change the version, it might not have overridden it with the updated package.

**Comment by kellylawson** [comment]
Hey @khouzam, 

I managed to get the updated dll imported - it looks like you were right, the nupkg was coming from a cache somewhere, and because it was the same version number I ended up just manually copying the new dll out of the .nupkg archive and placing it into my project to debug.  

Either way, it works and is ready to publish!  Thanks for taking care of that, and thanks to @vegorovinno for posting a suggested fix.  Let me know when the new version is published.

**Comment by jmvillagra** [comment]
I'm now having troubles building my solution with this new package:

4>error PRI175 : 0x80073b0f - Processing Resources failed with error : Duplicate Entry.
4>GENERATEPROJECTPRIFILE : error PRI277: 0xdef00532 - Conflicting values for resource ''
========== Rebuild All: 3 succeeded, 1 failed, 0 skipped ==========
I tried cleaning & deleting bin/obj but I can't make it work.

**Comment by khouzam** [comment]
Hi @jmvillagra 

Can you check that all your projects are referencing the same versions of the nuget package?

https://stackoverflow.com/a/51488478 seems to talk about a similar issue.

**Comment by khouzam** [comment]
Hi,

I've published the updated nuget package on the nuget.org feed. Please try to update your projects.

**Comment by kellylawson** [comment]
Works for me -  thanks again!

**Comment by khouzam** [comment]
I'll be closing this issue since it seems to have been addressed.
