### ISSUE TITLE
codegen.cmd doesn't detect updated input files & rebuild

### ISSUE THREAD

**Issue by TedHoward** [Microsoft/winsdkfb#30]
Low priority but it just broke our builds.

For now, I can add a quick hard-coded 'delete Generated folder' hack, either to codegen or to our build system. I looked at fixing it myself, but comparing filestamps in DOS is awful. I would switch to powershell.

**Comment by ekalbredneb** [comment]
Sorry, Ted.  Yes, it'll be some work to do the right thing here.  Originally I had codegen simply regenerate the files every time, but this breaks incremental building in the IDE, and after a short while it became clear that we couldn't tolerate rebuilding the entire project every time.  Given that, I'd recommend you make the hack in your build process rather than codegen.cmd for the time being - you'll save yourself some headaches in development.

**Comment by TedHoward** [comment]
I fully understand how & why it happened. We were just having a discussion on tech debt on our project today. We're all experienced enough to know that ugly and works is infinitely better than pretty and doesn't do much.

Thanks for all the work on the SDK. It's been quite useful. I'm sure I'll have a couple more PR's, maybe about login&token interaction and maybe about not being fullscreen on non-phone.

**Comment by yodurr** [comment]
preferred solution is codegen.cmd uses file timestamps to determine when to re-generate.

**Comment by adiviness** [comment]
f0bf0a2904805b86f85459e7a0b5cefad51e071c closes this issue.
