### ISSUE TITLE
Facebook game requests are not supported on the Universal Windows Platform

### ISSUE THREAD

**Issue by davidjdb** [Microsoft/winsdkfb#64]
Hi,

Could you please add support for them? https://developers.facebook.com/docs/games/requests/v2.4

Thanks

**Comment by alakshmi1030** [comment]
Just to clarify - you are only talking about the "Game Requests" feature and not all of the features listed under "Game Services", correct?

**Comment by TedHoward** [comment]
ShowRequestsDialog works for us.
The Facebook docs are not always so great. They often use 'game request', 'app request', and 'request' interchangeably. Even worse is it's not always the same thing - some are user-to-user and some are app-to-user. ShowRequestsDialog is user-to-user which is most often what you'll want in a game.

**Comment by alakshmi1030** [comment]
We do support game requests via the request dialog: http://microsoft.github.io/winsdkfb/#request_dialog
The app must be specified as type "game" in the Facebook Developer Portal.

**Comment by D4rkL1ch** [comment]
Hi,
I do have a question regarding the Game Requests.
We are during the development of Puzzle Craft 2 game for WUA and we are using App Invites on all other platforms (iOS, Android) - I have seen that we can only use game requests on WUA.
The problem is that when I am using the sample code from your wiki, it does not work, the case is:
1. user is logged in
2. I am invoking the game request - game opens webview, which tries to login user once again, but in the webview
3. after logging in, webview tells me that the access_token is wrong and nothing happens

Do you know if I require some additional permissions or some other things set up before using game requests with a WUA app?

Thanks for the response in advance!

Best regards,
Olgierd Rutkowski

**Comment by cbarkerms** [comment]
In your login code, try forcing the WebView to see if that helps:

await _session.LoginAsync(_permissions, SessionLoginBehavior.ForcingWebView);

**Comment by D4rkL1ch** [comment]
Hey,
thanks for the solution. We will try that and see how it works.

**Comment by adiviness** [comment]
Please feel free to reopen if this game requests problem is still being experienced.
