### ISSUE TITLE
WACK API Rejection

### ISSUE THREAD

**Issue by dupuisdavid** [Microsoft/winsdkfb#70]
Hi,

I'm using winsdkfb in my windows phone 8.1 project. All is ok for using, but I can't pass WACK API verification process due to the use of Sleep API (Module api-ms-win-core-synch-l1-2-0.dll) when I try to finalize my project exportation.
Here is the WACK (3.3) report (in french) : *Cette API n'est pas prise en charge pour ce type d'application - Api=Sleep. Module=api-ms-win-core-synch-l1-2-0.dll. Fichier=Facebook.dll*.
Indeed, Sleep function is not supported in windows phone apps on windows phone 8.1 platform : https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms686298%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396.

Any help ?
Thank you

**Comment by alakshmi1030** [comment]
Hey @dupuisdavid, we are looking into this right now.

**Comment by khouzam** [comment]
Hi @dupuisdavid,

I've looking into the issue and Sleep has been approved for use in the last version of WACK; the one that comes with the Windows 10 SDK and is also being applied to previous versions of applications so that you don't have to change your application code to still target Windows Phone 8.1.

Can you please try again with the latest WACK and confirm that the issue doesn't come up anymore?

Thanks
~Gilles
