### ISSUE TITLE
Like a Facebook Page with the graph api

### ISSUE THREAD

**Issue by RafaelPlantard** [Microsoft/winsdkfb#85]
How to like a facebook page by using this SDK, is it in the same way I like a page url?

**Comment by alakshmi1030** [comment]
Hey Rafael,

Our API supports the og.likes action as listed here: https://developers.facebook.com/docs/opengraph/guides/og.likes

You actually can't like a Facebook Page using our SDK, read the above link and check out our documentation to see why: http://microsoft.github.io/winsdkfb/

**Comment by RafaelPlantard** [comment]
Hey @alakshmi1030 I got it, that is a sad notice, I have other issue, I can login with this SDK, but the user information aka location, first name, last name, or other comes null, I can get only the full name and user id, what is the matter? And how about the e-mail how can I get it?

**Comment by RafaelPlantard** [comment]
thanks for advance.

**Comment by alakshmi1030** [comment]
Hey Rafael - the reason you can't get some of those fields is because we haven't yet added in all of the properties to pull from a user's profile. We are planning on adding these properties so that developers can pull information such as location. You should be able to retrieve the user's email however.

**Comment by RafaelPlantard** [comment]
Where is the e-mail?
How can I get it on C#?
